//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISRPO_Cherednichenko402_PR14.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pechi
    {
        public int idPech { get; set; }
        public string Name { get; set; }
        public int idColour { get; set; }
        public string Opisanie { get; set; }
        public decimal Cena { get; set; }
        public int Sklad { get; set; }
    
        public virtual Colour Colour { get; set; }
    }
}
